"""
PDF & Excel Export - Professional KRA-Ready Documents
Generates downloadable PDF reports and Excel workbooks from computed financial data.
"""

import io
import os
from datetime import datetime
from fpdf import FPDF
import pandas as pd
from backend.tax_calculator import (
    ProfitAndLoss, BalanceSheet, VATComputation, 
    PAYEComputation, IncomeTaxComputation, compute_income_tax,
)


class SMEAssistPDF(FPDF):
    """Custom PDF class with SME-Assist branding."""
    
    def __init__(self, business_name: str = "", period: str = ""):
        super().__init__()
        self.business_name = business_name
        self.period = period
        self.set_auto_page_break(auto=True, margin=20)
    
    def sanitize_text(self, text: str) -> str:
        """Sanitizes text to prevent FPDF Unicode encoding errors by replacing common special characters."""
        if not isinstance(text, str):
            text = str(text)
        # Replace common non-Latin1 characters
        replacements = {
            "\u2014": "-",  # em dash
            "\u2013": "-",  # en dash
            "\u201c": '"',  # curly double quote
            "\u201d": '"',  # curly double quote
            "\u2018": "'",  # curly single quote
            "\u2019": "'",  # curly single quote
            "\u2022": "*",  # bullet point
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        # Fallback: encode to Latin-1 and back to ignore other unsupported characters
        return text.encode("latin-1", "replace").decode("latin-1")
    
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(30, 64, 175)
        self.cell(0, 10, self.sanitize_text("SME-Assist"), new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, self.sanitize_text("AI-Powered Tax Compliance for Kenyan SMEs"), new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)
    
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by SME-Assist on {datetime.now().strftime('%d-%b-%Y %H:%M')} | Page {self.page_no()}", align="C")
    
    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 64, 175)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
    
    def business_header(self, biz_info: dict):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(20, 20, 20)
        self.cell(0, 8, self.sanitize_text(biz_info.get("business_name", "")), new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        details = f"KRA PIN: {biz_info.get('kra_pin', 'N/A')}  |  Bank: {biz_info.get('bank_name', '')}  |  A/C: {biz_info.get('account_number', '')}"
        self.cell(0, 6, self.sanitize_text(details), new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, self.sanitize_text(f"Period: {self.period}"), new_x="LMARGIN", new_y="NEXT")
        self.ln(6)
    
    def table_row(self, label: str, amount: float, bold: bool = False, indent: int = 0, color: str = "black"):
        prefix = "  " * indent
        style = "B" if bold else ""
        self.set_font("Helvetica", style, 10)
        
        if color == "green":
            self.set_text_color(0, 128, 0)
        elif color == "red":
            self.set_text_color(200, 0, 0)
        elif color == "blue":
            self.set_text_color(30, 64, 175)
        else:
            self.set_text_color(40, 40, 40)
        
        self.cell(120, 7, self.sanitize_text(f"{prefix}{label}"), border=0)
        
        amount_str = f"KES {abs(amount):,.2f}"
        if amount < 0:
            amount_str = f"(KES {abs(amount):,.2f})"
        
        self.cell(70, 7, amount_str, border=0, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(40, 40, 40)
    
    def separator(self, style: str = "thin"):
        y = self.get_y()
        if style == "thick":
            self.set_draw_color(30, 64, 175)
            self.set_line_width(0.5)
        else:
            self.set_draw_color(200, 200, 200)
            self.set_line_width(0.2)
        self.line(10, y, 200, y)
        self.ln(3)


def generate_pdf_report(
    biz_info: dict,
    pnl: ProfitAndLoss,
    bs: BalanceSheet,
    vat: VATComputation,
    employees: list[PAYEComputation],
    period: str = "",
) -> bytes:
    """Generates a complete PDF report and returns the bytes."""
    
    pdf = SMEAssistPDF(
        business_name=biz_info.get("business_name", ""),
        period=period
    )
    
    # ── Page 1: P&L ──
    pdf.add_page()
    pdf.business_header(biz_info)
    pdf.section_title("Profit & Loss Statement")
    
    pdf.table_row("Revenue", pnl.revenue, bold=True, color="green")
    pdf.table_row("Less: Cost of Goods Sold", -pnl.cost_of_goods_sold, indent=1, color="red")
    pdf.separator("thick")
    pdf.table_row("Gross Profit", pnl.gross_profit, bold=True, color="blue")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, pdf.sanitize_text(f"Gross Margin: {pnl.gross_margin:.1f}%"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, pdf.sanitize_text("Operating Expenses:"), new_x="LMARGIN", new_y="NEXT")
    
    for label, amount in sorted(pnl.expense_breakdown.items(), key=lambda x: -x[1]):
        if amount > 0:
            pdf.table_row(label, amount, indent=1)
    
    pdf.separator()
    pdf.table_row("Total Operating Expenses", pnl.total_operating_expenses, bold=True, color="red")
    pdf.separator("thick")
    pdf.table_row("Operating Profit", pnl.operating_profit, bold=True, color="blue")
    pdf.table_row("Less: Tax Provision", -pnl.tax_provision, indent=1)
    pdf.separator("thick")
    pdf.table_row("NET PROFIT", pnl.net_profit, bold=True, color="green" if pnl.net_profit >= 0 else "red")
    
    # ── Page 2: Balance Sheet ──
    pdf.add_page()
    pdf.section_title("Statement of Financial Position (Balance Sheet)")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, pdf.sanitize_text(f"As at {bs.period} | IFRS for SMEs"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 8, "ASSETS", new_x="LMARGIN", new_y="NEXT")
    
    pdf.table_row("Cash & Bank Balances", bs.cash_and_bank, indent=1)
    pdf.table_row("Inventory (Estimated)", bs.inventory, indent=1)
    pdf.separator()
    pdf.table_row("Total Current Assets", bs.total_current_assets, bold=True)
    pdf.ln(2)
    pdf.table_row("Equipment & Assets", bs.equipment, indent=1)
    pdf.table_row("Less: Accumulated Depreciation", -bs.less_depreciation, indent=1, color="red")
    pdf.table_row("Total Non-Current Assets", bs.total_non_current_assets, bold=True)
    pdf.separator("thick")
    pdf.table_row("TOTAL ASSETS", bs.total_assets, bold=True, color="blue")
    
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 8, "LIABILITIES", new_x="LMARGIN", new_y="NEXT")
    
    pdf.table_row("VAT Payable", bs.vat_payable, indent=1)
    pdf.table_row("Income Tax Payable", bs.other_tax_payable, indent=1)
    pdf.separator()
    pdf.table_row("Total Liabilities", bs.total_liabilities, bold=True, color="red")
    
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 128, 0)
    pdf.cell(0, 8, "EQUITY", new_x="LMARGIN", new_y="NEXT")
    
    pdf.table_row("Retained Earnings", bs.retained_earnings, indent=1)
    pdf.table_row("Current Period Profit", bs.current_period_profit, indent=1, color="green")
    pdf.separator("thick")
    pdf.table_row("TOTAL EQUITY + LIABILITIES", bs.total_equity + bs.total_liabilities, bold=True, color="blue")
    
    # ── Page 3: VAT Return ──
    pdf.add_page()
    pdf.section_title("VAT-3 Return Computation")
    
    pdf.table_row("Total Sales (VAT Inclusive)", vat.total_sales_incl_vat)
    pdf.table_row("Total Sales (VAT Exclusive)", vat.total_sales_excl_vat)
    pdf.table_row("OUTPUT VAT (Collected)", vat.output_vat, bold=True, color="red")
    pdf.ln(4)
    pdf.table_row("Total Purchases (VAT Inclusive)", vat.total_purchases_incl_vat)
    pdf.table_row("Total Purchases (VAT Exclusive)", vat.total_purchases_excl_vat)
    pdf.table_row("INPUT VAT (Claimable)", vat.input_vat, bold=True, color="green")
    pdf.separator("thick")
    pdf.table_row("NET VAT PAYABLE TO KRA", vat.net_vat_payable, bold=True, color="blue")
    
    # ── Page 4: PAYE Schedule ──
    if employees:
        pdf.add_page()
        pdf.section_title("PAYE Schedule (P10)")
        
        # Table header
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(240, 240, 250)
        headers = ["Employee", "Gross (KES)", "NSSF", "PAYE", "SHIF", "H.Levy", "Net Pay"]
        widths = [50, 25, 20, 25, 20, 20, 30]
        
        for i, h in enumerate(headers):
            pdf.cell(widths[i], 7, h, border=1, fill=True, align="C")
        pdf.ln()
        
        pdf.set_font("Helvetica", "", 8)
        for emp in employees:
            vals = [
                emp.employee_name[:20],
                f"{emp.gross_salary:,.0f}",
                f"{emp.nssf_employee:,.0f}",
                f"{emp.net_paye:,.0f}",
                f"{emp.shif:,.0f}",
                f"{emp.housing_levy:,.0f}",
                f"{emp.net_salary:,.0f}",
            ]
            for i, v in enumerate(vals):
                align = "L" if i == 0 else "R"
                pdf.cell(widths[i], 6, pdf.sanitize_text(v), border=1, align=align)
            pdf.ln()
    
    # ── Page 5: Tax Intelligence ──
    pdf.add_page()
    income_tax = compute_income_tax(pnl)
    pdf.section_title("Tax Intelligence Summary")
    
    pdf.table_row("Total Revenue", pnl.revenue, color="green")
    pdf.table_row("Total Deductible Expenses", income_tax.total_deductible_expenses)
    pdf.table_row("Taxable Income", income_tax.taxable_income, bold=True)
    pdf.separator()
    pdf.table_row("Corporate Income Tax (30%)", income_tax.tax_payable, color="red")
    if income_tax.qualifies_for_tot:
        pdf.table_row("Turnover Tax Option (3%)", income_tax.tot_amount, color="green")
    pdf.separator("thick")
    
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 7, pdf.sanitize_text(f"Recommendation: {income_tax.recommended_regime}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, pdf.sanitize_text(f"Effective Tax Rate: {income_tax.effective_tax_rate:.1f}%"), new_x="LMARGIN", new_y="NEXT")
    
    # Output
    return bytes(pdf.output())


def generate_excel_report(
    biz_info: dict,
    df: pd.DataFrame,
    pnl: ProfitAndLoss,
    vat: VATComputation,
    employees: list[PAYEComputation],
) -> bytes:
    """Generates an Excel workbook with multiple sheets."""
    
    output = io.BytesIO()
    
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        # Sheet 1: Transactions
        export_df = df[["date", "description", "reference", "debit", "credit", "balance", "category_label", "is_deductible"]].copy()
        export_df.columns = ["Date", "Description", "Reference", "Debit (KES)", "Credit (KES)", "Balance", "Category", "Tax Deductible"]
        export_df.to_excel(writer, sheet_name="Transactions", index=False)
        
        # Sheet 2: P&L
        pnl_data = {
            "Item": ["Revenue", "Cost of Goods Sold", "Gross Profit", ""],
            "Amount (KES)": [pnl.revenue, -pnl.cost_of_goods_sold, pnl.gross_profit, ""],
        }
        for label, amount in pnl.expense_breakdown.items():
            pnl_data["Item"].append(f"  {label}")
            pnl_data["Amount (KES)"].append(-amount)
        
        pnl_data["Item"].extend(["", "Total Operating Expenses", "Operating Profit", "Tax Provision", "NET PROFIT"])
        pnl_data["Amount (KES)"].extend(["", -pnl.total_operating_expenses, pnl.operating_profit, -pnl.tax_provision, pnl.net_profit])
        
        pd.DataFrame(pnl_data).to_excel(writer, sheet_name="Profit & Loss", index=False)
        
        # Sheet 3: VAT
        vat_data = {
            "Item": [
                "Total Sales (Incl VAT)", "Total Sales (Excl VAT)", "Output VAT",
                "", "Total Purchases (Incl VAT)", "Total Purchases (Excl VAT)", "Input VAT",
                "", "NET VAT PAYABLE"
            ],
            "Amount (KES)": [
                vat.total_sales_incl_vat, vat.total_sales_excl_vat, vat.output_vat,
                "", vat.total_purchases_incl_vat, vat.total_purchases_excl_vat, vat.input_vat,
                "", vat.net_vat_payable
            ],
        }
        pd.DataFrame(vat_data).to_excel(writer, sheet_name="VAT-3 Return", index=False)
        
        # Sheet 4: PAYE
        if employees:
            emp_data = [{
                "Employee": e.employee_name,
                "Gross Salary": e.gross_salary,
                "NSSF": e.nssf_employee,
                "Taxable Pay": e.taxable_pay,
                "PAYE Tax": e.paye_tax,
                "Personal Relief": e.personal_relief,
                "Net PAYE": e.net_paye,
                "SHIF": e.shif,
                "Housing Levy": e.housing_levy,
                "Net Salary": e.net_salary,
            } for e in employees]
            pd.DataFrame(emp_data).to_excel(writer, sheet_name="PAYE Schedule", index=False)
        
        # Sheet 5: Category Summary
        from backend.categorizer import get_category_summary
        summary = get_category_summary(df)
        summary.to_excel(writer, sheet_name="Category Summary", index=False)
    
    return output.getvalue()
